right_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - right_joint1
        - right_joint2
        - right_joint3
        - right_joint4
        - right_virtual_roll_joint
        - right_virtual_yaw_joint
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        right_joint1: {trajectory: 0.1, goal: 0.1}
        right_joint2: {trajectory: 0.1, goal: 0.1}
        right_joint3: {trajectory: 0.1, goal: 0.1}
        right_joint4: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  30
    action_monitor_rate: 10

left_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - left_joint1
        - left_joint2
        - left_joint3
        - left_joint4
        - left_virtual_roll_joint
        - left_virtual_yaw_joint
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        left_joint1: {trajectory: 0.1, goal: 0.1}
        left_joint2: {trajectory: 0.1, goal: 0.1}
        left_joint3: {trajectory: 0.1, goal: 0.1}
        left_joint4: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

right_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
      - right_gripper
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      gripper: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains: # Required because we're controlling an effort interface
    right_gripper: {p: 100,  d: 1, i: 1, i_clamp: 1}
    
    
left_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
      - left_gripper
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      gripper: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains: # Required because we're controlling an effort interface
    left_gripper: {p: 100,  d: 1, i: 1, i_clamp: 1}
    
    
    
