left_joint1:
  ID: 21
left_joint2:
  ID: 22
left_joint3:
  ID: 23
left_joint4:
  ID: 24
left_gripper:
  ID: 25
 
right_joint1:
  ID: 11
right_joint2:
  ID: 12
right_joint3:
 ID: 13
right_joint4:
  ID: 14
right_gripper:
  ID: 15
