controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_virtual_roll_joint
      - right_virtual_yaw_joint
  - name: fake_left_arm_controller
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_virtual_roll_joint
      - left_virtual_yaw_joint
  - name: fake_right_gripper_controller
    joints:
      - right_gripper
  - name: fake_left_gripper_controller
    joints:
      - left_gripper
  - name: fake_dual_arms_controller
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4

